spring:
  application:
    name: messenger-io
server:
  port: 8585
logging:
  level:
    root: info
    com.cyberalexander.messengerio: debug

twilio:
  account_sid: #SECURED#
  auth_token: #SECURED#
  from_number: #SECURED#

