spring:
  application:
    name: messenger-io
server:
  port: 8585
logging:
  level:
    root: info

twilio:
  account_sid: AC8482ab98ecea707b0c5fd637a961fcae
  auth_token: 5f8134e4024bb1c9c8da97119bcd0674
  from_number: #SECURED#

